### ISSUE TITLE
liquid-node version

### ISSUE THREAD

**Issue by juanbrujo** [mrcljx/grunt-liquid#13]
Lots of filters are missing in this version from https://github.com/sirlantis/liquid-node/blob/master/src/liquid/standard_filters.coffee. I'm porting them mannualy, but how is possible to have it updated?

**Comment by juanbrujo** [comment]
I noticed it is using 0.2.0 of liquid-node and and the current version is 2.0.0.

**Comment by mrcljx** [comment]
Hey @juanbrujo,

I just uploaded grunt-liquid `2.0.0` which will use liquid-node `2.0.0`. It will also allow you to register custom filters within your Gruntfile (see https://github.com/sirlantis/grunt-liquid/blob/842932d526af021f034019d204eb550ce0291b2c/Gruntfile-test.js#L7-L17).

**Comment by juanbrujo** [comment]
Thanks @sirlantis but the 2.0.0 version broke many things (ex. the variable definition through {% asign %} ), I should make a review of the changes from the previous 0.1.0 version before using it in a real project.
