### ISSUE TITLE
problem with asign

### ISSUE THREAD

**Issue by juanbrujo** [mrcljx/grunt-liquid#14]
Since 2.0 version I'm having problems asigning a variable, like:

{% assign name = "Name" %}
{{ name }}

returning nothing

**Comment by juanbrujo** [comment]
OK this is weird, it works if assign y declared after calling it:
{{ name }}
{% assign name = "Name" %}

Same with capture:
{{ capturing }}
{% capture capturing %}Capturing.{% endcapture %}

**Comment by developher-net** [comment]
I'm seeing this when the variable is assigned in a parent template, and then acted upon in an included template. The variable doesn't work unless defined in the same template where it's used.

This works fine if I revert to v0.2.0

**Comment by juanbrujo** [comment]
@amclin yep, had to downgrade to 0.2.0 too

**Comment by mrcljx** [comment]
This was an issue in liquid-node and got fixed in sirlantis/liquid-node@38b3fed0bad95be7d797f497cd7a45e7ee34c1d4 and the is available in liquid-node 2.1.4.
