### ISSUE TITLE
Incorrect version for Node dependency

### ISSUE THREAD

**Issue by developher-net** [mrcljx/grunt-liquid#15]
The following warning is displayed when installing grunt-liquid:
`npm WARN engine grunt-liquid@2.0.0: wanted: {"node":">= 1.0.0"} (current: {"node":"v0.10.28","npm":"1.4.9"})`

There is no Node v1.0.0 or later. The last stable release of Node.JS is v0.10.30:
http://nodejs.org/

**Comment by saddam-azad** [comment]
Yes, package.json line 24 needs to be updated. Node 1.0.0 doesn't exist. Please update.
