### ISSUE TITLE
not on npm as specified

### ISSUE THREAD

**Issue by davidmarkclements** [mrcljx/grunt-liquid#3]
**npm install grunt-liquid --save-dev**

npm WARN package.json 13Coins@0.1.0 No README.md file found!
npm http GET https://registry.npmjs.org/grunt-liquid
npm http 404 https://registry.npmjs.org/grunt-liquid
npm ERR! 404 'grunt-liquid' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.8.0-26-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-liquid" "--save-dev"
npm ERR! cwd /home/dave/Dropbox/13coins
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dave/Dropbox/13coins/npm-debug.log
npm ERR! not ok code 0

**Comment by mrcljx** [comment]
Whoopsey! Fixed that. :)
