### ISSUE TITLE
Bump the version number

### ISSUE THREAD

**Issue by arminrosu** [mrcljx/grunt-liquid#5]
Hey,

Thanks for the plugin. Currently I had only 1 issue with it, installing it as a dependcy pulls an older version, which doesn't have `includes` support. Maybe bumping the version number would help, so the registry would update it.

Thanks :)

**Comment by mrcljx** [comment]
Hi @arminrosu!
I just bumped the version number and https://npmjs.org/package/grunt-liquid now shows the correct version with `includes` support. :)

**Comment by arminrosu** [comment]
awesome, thanks :)
